# Reminder for dev
# To use local jekyll-admin: bundle config local.jekyll-admin /workspaces/lprp/jekyll-admin/
# To ignore windows mode changes: git config core.filemode false

# Override settings for dev mode
title: '[dev] LPRP.fr'

# Remove generation of archives in development to speed up things
jekyll-archives:
  enabled: []

show_drafts: true

# jekyll-admin do not handle well multiple config files, so this has to be done in the main one
jekyll_admin:
  homepage: drafts
